steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/ship-date-drift/orchestrator-frontend:memories
      - --build-arg
      - REACT_APP_API_URL=https://orchestrator-backend-icnkyenovq-uc.a.run.app/api
      - --build-arg
      - REACT_APP_WS_URL=wss://orchestrator-backend-icnkyenovq-uc.a.run.app/ws
      - .
images:
  - gcr.io/ship-date-drift/orchestrator-frontend:memories
options:
  logging: CLOUD_LOGGING_ONLY
