steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'REACT_APP_API_URL=https://orchestrator-backend-icnkyenovq-uc.a.run.app/api'
      - '--build-arg'
      - 'REACT_APP_WS_URL=wss://orchestrator-backend-icnkyenovq-uc.a.run.app/ws'
      - '-t'
      - 'gcr.io/ship-date-drift/orchestrator-frontend:v1'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/ship-date-drift/orchestrator-frontend:v1'
images:
  - 'gcr.io/ship-date-drift/orchestrator-frontend:v1'
