"""
ADK Callbacks – Model Armor Safety Hooks
==========================================
ADK before_model and after_model callbacks that integrate the Model Armor
firewall inline with every agent invocation, matching the spec's requirement
that ALL inbound unstructured inputs are screened before the model sees them.

Spec reference: §3.E – Model Armor inline filtering for prompt injection,
tool poisoning, and PII masking.
"""

from typing import Optional
from google.adk.agents.callback_context import CallbackContext
from google.adk.models.llm_request import LlmRequest
from google.adk.models.llm_response import LlmResponse
from google.genai import types as genai_types
import tool_server_client as client


# ── Threat categories that should hard-block the request ─────────────────────
BLOCKING_THREAT_TYPES = {"PROMPT_INJECTION", "JAILBREAK_ATTEMPT"}


def model_armor_before_model_callback(
    callback_context: CallbackContext,
    llm_request: LlmRequest,
) -> Optional[LlmResponse]:
    """
    ADK before_model callback — runs BEFORE every Gemini model call.

    1. Extracts the last user message from the request contents.
    2. Submits it to the Node.js Model Armor endpoint.
    3. If threats are detected → returns a blocking LlmResponse (short-circuits
       the model call entirely — Gemini never sees the payload).
    4. If PII was masked → replaces the message text with the sanitised version.
    5. Stores scan metadata in the session state for observability.
    """
    # Extract the last user message text from the request
    user_text = ""
    if llm_request.contents:
        for content in reversed(llm_request.contents):
            if content.role == "user":
                for part in (content.parts or []):
                    if hasattr(part, "text") and part.text:
                        user_text = part.text
                        break
                if user_text:
                    break

    if not user_text:
        return None  # nothing to scan

    # Call Model Armor
    try:
        scan_result = client.armor_scan({"text": user_text})
    except Exception as exc:
        # Tool-server unreachable — log but don't block (fail-open for resilience)
        callback_context.state["armor_scan_error"] = str(exc)
        return None

    threats = scan_result.get("threats", [])
    is_safe = scan_result.get("safe", True)
    pii_masked = scan_result.get("piiMasked", False)
    scan_id = scan_result.get("scanId", "")

    # Store in session state for downstream observability
    callback_context.state["last_armor_scan"] = {
        "scan_id": scan_id,
        "safe": is_safe,
        "threats": threats,
        "pii_masked": pii_masked,
    }

    if not is_safe:
        # Hard-block: return a synthetic response that never reaches the model
        blocking_types = [t["type"] for t in threats if t["type"] in BLOCKING_THREAT_TYPES]
        block_message = (
            f"[MODEL ARMOR BLOCKED] Request was blocked due to detected threats: "
            f"{', '.join(blocking_types)}. Scan ID: {scan_id}."
        )
        return LlmResponse(
            content=genai_types.Content(
                role="model",
                parts=[genai_types.Part(text=block_message)],
            )
        )

    # If PII was masked, replace the user message in the request
    if pii_masked:
        sanitized_text = scan_result.get("sanitized", {}).get("text", user_text)
        if llm_request.contents:
            for content in reversed(llm_request.contents):
                if content.role == "user":
                    for part in (content.parts or []):
                        if hasattr(part, "text") and part.text:
                            part.text = sanitized_text
                            break
                    break

    return None  # continue normally


def model_armor_after_model_callback(
    callback_context: CallbackContext,
    llm_response: LlmResponse,
) -> Optional[LlmResponse]:
    """
    ADK after_model callback — runs AFTER every Gemini model call.

    Scans the model output for Data Loss Prevention (DLP) violations:
    any residual PII or sensitive data inadvertently generated by the model
    is masked before the response reaches the caller.

    Spec reference: §3.E – DLP & Tool Poisoning Prevention on agent outputs.
    """
    if not llm_response or not llm_response.content:
        return None

    output_text = ""
    for part in (llm_response.content.parts or []):
        if hasattr(part, "text") and part.text:
            output_text += part.text

    if not output_text:
        return None

    # Run output through DLP scan
    try:
        scan_result = client.armor_scan({"text": output_text})
    except Exception:
        return None  # fail-open

    if scan_result.get("piiMasked"):
        sanitized = scan_result.get("sanitized", {}).get("text", output_text)
        # Replace output parts with sanitised version
        new_parts = []
        for part in (llm_response.content.parts or []):
            if hasattr(part, "text") and part.text:
                new_parts.append(genai_types.Part(text=sanitized))
            else:
                new_parts.append(part)
        return LlmResponse(
            content=genai_types.Content(role="model", parts=new_parts)
        )

    return None  # no modification needed
